packages:
  - 'apps/*'

catalogs:
  default:
    typescript: ^5.7.2
    vitest: ^4.0.18
    '@vitest/coverage-v8': ^4.0.18
    vite: ^6.0.6
    react: ^19.2.4
    react-dom: ^19.2.4
    '@types/react': ^19.2.14
    '@types/react-dom': ^19.0.2
    jsdom: ^27.4.0
